#!/bin/bash

docker build --no-cache -f ./cs-base.dockerfile -t 10security/cs-base:1.3.8 -t 10security/cs-base:latest .

docker build --no-cache -f ./cs-ssllabs.dockerfile -t 10security/cs-ssllabs:1.4.0 -t 10security/cs-ssllabs:latest .

docker build --no-cache -f ./cs-git-bad1.dockerfile -t 10security/cs-git-bad1:2.25.1 -t 10security/cs-git-bad1:latest .

docker build --build-arg CLOUD_PROVIDER_SECRET_KEY=iequooWang4a --no-cache -f ./cs-git-bad2.dockerfile -t 10security/cs-git-bad2:2.25.1 -t 10security/cs-git-bad2:latest .

docker build --no-cache -f ./cs-cloc.dockerfile -t 10security/cs-cloc:1.82 -t 10security/cs-cloc:latest .

